fix resume

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -21,14 +21,23 @@ jobs:
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
-          node-version: "20"
+          node-version: "18"
           cache: 'npm'
+        
+      - name: Clear npm cache
+        run: npm cache clean --force
 
       - name: Install dependencies
         run: npm install
 
       - name: Build project
         run: npm run build
+        
+      - name: Debug Build Output
+        run: ls -la ./dist
+
+      - name: Ensure CNAME exists
+        run: test -f CNAME && echo "CNAME found" || echo "CNAME not found
 
       - name: Copy CNAME to Build Directory
         run: cp CNAME ./dist/CNAME  # Копируем файл CNAME в директорию dist
@@ -37,6 +46,7 @@ jobs:
         uses: actions/upload-pages-artifact@v3
         with:
           path: ./dist
+          name: github-pages
 
   deploy:
     environment:
